require("shket.cmp")
-- require("shket.autopairs")
require("shket.lsp")
require("shket.null-ls")
require("shket.treesitter")
require("shket.lualine")
require("shket.autosave")
require("shket.telescope")
require("shket.colorscheme")
-- require("shket.specific")
require("shket.comment")
-- require("shket.util")

-- require("jupyter-nvim").setup()
