
require("shket.cmp")
require("shket.autopairs")
require("shket.lsp")
require("shket.null-ls")
require("shket.treesitter")
require("shket.lualine")
require("shket.autosave")
require("shket.telescope")
-- require("shket.colors")
require("shket.comment")
require("shket.aerial")

require("shket.specific")
-- require("jupyter-nvim").setup()
